import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

type Role='VIEWER'|'OPERATOR'|'ADMIN';
type Session={authenticated:boolean;user?:string;role?:Role;csrfToken?:string};
type Desired={target_bundle_id:string|null;previous_bundle_id:string|null;rollout_percent:number;updated_by:string|null;updated_at:string|null};
type Bundle={bundle_id:string;revision:number;sha256:string;content_bytes:number;status:string;created_by:string|null;created_at:string;activated_at:string|null};
type Agent={agent_id:string;display_name:string;platform:string|null;arch:string|null;installed_bundle_id:string|null;active_bundle_id:string|null;active_revision:number|null;active_sha256:string|null;desired_bundle_id:string|null;state:string;error:string|null;last_ack_at:string|null};
type Overview={desired:Desired;bundles:Bundle[];agents:Agent[]};
type ApiError={error?:string};

async function getJson<T>(path:string):Promise<T>{const r=await fetch(path,{headers:{accept:'application/json'},credentials:'same-origin'});if(!r.ok){const b=await r.json().catch(()=>({} as ApiError)) as ApiError;throw new Error(b.error??`HTTP ${r.status}`);}return r.json() as Promise<T>;}
async function postJson<T>(path:string,body:unknown,session:Session):Promise<T>{const r=await fetch(path,{method:'POST',credentials:'same-origin',headers:{accept:'application/json','content-type':'application/json','x-neta-portal-request':'1','x-neta-portal-csrf':session.csrfToken??'','idempotency-key':`yarax-content:${crypto.randomUUID()}`},body:JSON.stringify(body)});if(!r.ok){const b=await r.json().catch(()=>({} as ApiError)) as ApiError;throw new Error(b.error??`HTTP ${r.status}`);}return r.json() as Promise<T>;}
function Badge({v}:{v:string}){const n=v.toLowerCase();const tone=n.includes('failed')||n.includes('unsupported')?'danger':n.includes('stale')?'warn':n.includes('active')?'ok':'muted';return <span className={`badge ${tone}`}>{v}</span>;}

export default function YaraContent(){
  const qc=useQueryClient();
  const session=useQuery({queryKey:['session'],queryFn:()=>getJson<Session>('/portal-api/auth/session')});
  const q=useQuery({queryKey:['yarax-content'],queryFn:()=>getJson<Overview>('/portal-api/yarax/content'),enabled:Boolean(session.data?.authenticated&&(session.data.role==='OPERATOR'||session.data.role==='ADMIN')),refetchInterval:10000});
  const[bundleId,setBundleId]=useState(''); const[content,setContent]=useState(''); const[percent,setPercent]=useState(5); const[notice,setNotice]=useState('');
  const publish=useMutation({mutationFn:()=>postJson<{bundleId:string;sha256:string;revision:number}>('/portal-api/yarax/content/publish',{bundleId,content,rolloutPercent:percent},session.data??{authenticated:false}),onSuccess:async r=>{setNotice(`Published ${r.bundleId} revision ${r.revision}; SHA-256 ${r.sha256}.`);await qc.invalidateQueries({queryKey:['yarax-content']});}});
  const rollout=useMutation({mutationFn:()=>postJson('/portal-api/yarax/content/rollout',{bundleId:q.data?.desired.target_bundle_id,rolloutPercent:percent},session.data??{authenticated:false}),onSuccess:async()=>{setNotice(`Rollout changed to ${percent}%.`);await qc.invalidateQueries({queryKey:['yarax-content']});}});
  if(session.isLoading)return <main><div className="panel loading">Loading…</div></main>;
  if(!session.data?.authenticated)return <main><div className="notice danger-notice">Sign in to NETA first. <a href="/">Open portal</a></div></main>;
  if(session.data.role!=='OPERATOR'&&session.data.role!=='ADMIN')return <main><div className="notice danger-notice">OPERATOR or ADMIN role is required.</div></main>;
  const d=q.data?.desired; const agents=q.data?.agents??[]; const bundles=q.data?.bundles??[]; const isAdmin=session.data.role==='ADMIN';
  return <main><header className="page-header"><div><h1>YARA content</h1><p>RM4.4 centrally managed detection content</p></div><a className="secondary" href="/rules">Back to Rules</a></header>
    <div className="notice">YARA content is policy data consumed only by the trusted endpoint YARA-X evaluator. Agents fetch it over mTLS, verify the coordinator-pinned SHA-256, atomically activate it, restart the detector, and ACK state. This is not arbitrary remote code execution.</div>
    {d&&<div className="cards" style={{marginTop:'16px'}}><div className="metric-card"><div className="metric-title">Desired bundle</div><div className="metric-value">{d.target_bundle_id??'-'}</div><div className="metric-detail">Previous {d.previous_bundle_id??'-'}</div></div><div className="metric-card"><div className="metric-title">Rollout</div><div className="metric-value">{d.rollout_percent}%</div><div className="metric-detail">{agents.filter(a=>a.state==='ACTIVE'&&a.active_bundle_id===d.target_bundle_id).length}/{agents.length} endpoints active on target</div></div></div>}
    {isAdmin&&<div className="panel action-form"><h3>Publish immutable YARA bundle</h3><div className="form-grid"><label>Bundle ID<input value={bundleId} onChange={e=>setBundleId(e.target.value)} placeholder="rm4-central-1"/></label><label>Initial rollout<select value={percent} onChange={e=>setPercent(Number(e.target.value))}><option value={0}>0% paused</option><option value={5}>5% canary</option><option value={25}>25%</option><option value={50}>50%</option><option value={100}>100%</option></select></label></div><label>YARA source<textarea value={content} onChange={e=>setContent(e.target.value)} rows={14} placeholder={'rule NETA_EXAMPLE {\n  strings:\n    $marker = "example"\n  condition:\n    $marker\n}'}/></label><button disabled={publish.isPending||!bundleId.trim()||!content.trim()} onClick={()=>confirm(`Publish immutable YARA content bundle ${bundleId}?`)&&publish.mutate()}>{publish.isPending?'Publishing…':'Publish bundle'}</button>{publish.error&&<div className="notice danger-notice">{(publish.error as Error).message}</div>}</div>}
    {isAdmin&&d?.target_bundle_id&&<div className="panel action-form"><h3>Staged rollout</h3><div className="row-actions"><select value={percent} onChange={e=>setPercent(Number(e.target.value))}><option value={0}>0% pause</option><option value={5}>5% canary</option><option value={25}>25%</option><option value={50}>50%</option><option value={100}>100% fleet</option></select><button disabled={rollout.isPending} onClick={()=>rollout.mutate()}>Apply rollout</button></div></div>}
    {notice&&<div className="notice" style={{marginTop:'12px'}}>{notice}</div>}
    {q.isLoading?<div className="panel loading">Loading YARA content state…</div>:q.error?<div className="panel error-panel">{(q.error as Error).message}</div>:<><div className="panel table-panel"><div className="table-summary">Endpoint content coverage</div><div className="table-wrap"><table><thead><tr><th>Endpoint</th><th>Platform</th><th>Desired</th><th>Active</th><th>Revision</th><th>State</th><th>Last ACK</th><th>Error</th></tr></thead><tbody>{agents.map(a=><tr key={a.agent_id}><td>{a.display_name}<div className="mono">{a.agent_id}</div></td><td>{a.platform??'-'}{a.arch?`/${a.arch}`:''}</td><td>{a.desired_bundle_id??'-'}</td><td>{a.active_bundle_id??'-'}</td><td>{a.active_revision??'-'}</td><td><Badge v={a.state}/></td><td>{a.last_ack_at??'-'}</td><td>{a.error??'-'}</td></tr>)}</tbody></table></div></div><div className="panel table-panel"><div className="table-summary">Published immutable bundles</div><div className="table-wrap"><table><thead><tr><th>Bundle</th><th>Revision</th><th>SHA-256</th><th>Bytes</th><th>Status</th><th>Created</th></tr></thead><tbody>{bundles.map(b=><tr key={b.bundle_id}><td>{b.bundle_id}</td><td>{b.revision}</td><td className="mono">{b.sha256}</td><td>{b.content_bytes}</td><td><Badge v={b.status}/></td><td>{b.created_at}</td></tr>)}</tbody></table></div></div></>}
  </main>;
}
